/**
 * ALMS "Food Matters — Beyond the Plate" News Corner
 * Interactive news & story carousel with auto-transition, manual swipe/navigation,
 * category badges, modal reader, and humanitarian food security focus.
 */

const ALMS_NEWS = {
  currentIndex: 0,
  autoTimer: null,

  articles: [
    {
      id: 'news-1',
      badge: 'India Focus',
      category: 'Food Rescue',
      title: 'When Food Goes to Waste, Someone Else May Go Without',
      summary: 'Over 68 million tonnes of food is wasted annually in India while millions face micro-nutrient deficiencies. Community rescue networks are bridging this crucial divide.',
      image: 'images/children-meal.jpeg',
      date: 'Aug 2026 • National Food Watch',
      readTime: '3 min read',
      fullContent: `
        <p>In banquet halls, tech parks, and university hostels, tonnes of freshly prepared, untouched surplus food is discarded every single evening. Meanwhile, shelters, orphanages, and daily wage families within a 5 km radius struggle for access to balanced meals.</p>
        <p>Decentralized food rescue networks like ALMS leverage hyper-local matching algorithms and volunteer dispatch to divert surplus within safe shelf-life windows. Every kilogram diverted not only restores human dignity but prevents potent methane emissions generated by decomposing organics in municipal landfills.</p>
      `
    },
    {
      id: 'news-2',
      badge: 'Climate Impact',
      category: 'Environment',
      title: 'The Hidden Carbon Footprint of Wasted Banquet Meals',
      summary: 'Diverting 100 kg of edible food prevents nearly 85 kg of direct CO₂ equivalent greenhouse gases from heating the atmosphere.',
      image: 'images/community-meal.jpeg',
      date: 'Aug 2026 • Eco-Impact Journal',
      readTime: '4 min read',
      fullContent: `
        <p>Food loss is not solely an ethical tragedy — it is the third largest emitter of greenhouse gases globally if ranked as a country. When food rots in an anaerobic landfill, it generates methane, a gas 28 times more potent than carbon dioxide at trapping atmospheric heat.</p>
        <p>By connecting commercial kitchens with immediate volunteer pickup, ALMS ensures food reaches empty plates within hours of preparation, conserving both agricultural energy and urban ecosystems.</p>
      `
    },
    {
      id: 'news-3',
      badge: 'Human Story',
      category: 'Community Smiles',
      title: 'How One Campus Mess Fed 400 Street Children Weekly',
      summary: 'A university in Delhi collaborated with ALMS to systematically channel weekend mess surplus into local evening shelter homes.',
      image: 'images/sharing.jpeg',
      date: 'Aug 2026 • Community Spotlight',
      readTime: '2 min read',
      fullContent: `
        <p>Every Saturday, student coordinators at a central university mess log surplus rice and lentils onto ALMS. Within 12 minutes, verified local volunteers arrive with sanitized vessels, packing nutritious hot meals for children in nearby transit camps.</p>
        <p>“We turned what used to be painful waste into smiles and celebration,” says student coordinator Aditi. “The entire campus now takes pride in zero waste.”</p>
      `
    },
    {
      id: 'news-4',
      badge: 'Policy & Innovation',
      category: 'FSSAI Standards',
      title: 'Smart Hygiene Guidelines Make Surplus Donation Safer',
      summary: 'New food donation safety frameworks provide clear protocols on container sealing, temperature retention, and safe transport windows.',
      image: 'images/meal-distribution.jpeg',
      date: 'Aug 2026 • Food Safety Standards',
      readTime: '3 min read',
      fullContent: `
        <p>Standardized food safety guidelines now empower restaurants and hotels to donate surplus without fear of legal liability, provided the food is hot-held or flash-chilled properly. ALMS embeds vessel capacity matching into every bulk donation workflow to guarantee safe food transit.</p>
      `
    }
  ],

  init(containerId = 'newsCarouselContainer') {
    this.render(containerId);
    this.startAutoPlay();
  },

  render(containerId = 'newsCarouselContainer') {
    const el = document.getElementById(containerId);
    if (!el) return;

    el.innerHTML = `
      <div class="news-carousel">
        <div class="news-track" id="newsTrack" style="transform: translateX(-${this.currentIndex * 33.333}%);">
          ${this.articles.map(art => `
            <div class="news-card">
              <div class="news-card-img-wrap">
                <img src="${art.image}" alt="${art.title}" class="news-card-image" onerror="this.src='images/sharing.jpeg'">
                <span class="news-card-latest">${art.badge}</span>
              </div>
              <div class="news-card-body">
                <div class="news-card-source">${art.category} • ${art.readTime}</div>
                <h3 class="news-card-title">${art.title}</h3>
                <p class="news-card-summary">${art.summary}</p>
                <div class="news-card-footer">
                  <span>${art.date}</span>
                  <button class="btn btn-sm btn-outline" onclick="ALMS_NEWS.openArticle('${art.id}')">
                    Read Story →
                  </button>
                </div>
              </div>
            </div>
          `).join('')}
        </div>
      </div>

      <div class="news-nav">
        <button class="news-nav-btn" onclick="ALMS_NEWS.prev()" title="Previous Article">‹</button>
        <div class="news-dots" id="newsDots">
          ${this.articles.map((_, i) => `
            <button class="news-dot ${i === this.currentIndex ? 'active' : ''}" onclick="ALMS_NEWS.goTo(${i})"></button>
          `).join('')}
        </div>
        <button class="news-nav-btn" onclick="ALMS_NEWS.next()" title="Next Article">›</button>
      </div>

      <!-- Story Modal -->
      <div id="newsStoryModal" class="modal-backdrop" onclick="ALMS_NEWS.closeModal(event)">
        <div class="modal" onclick="event.stopPropagation()">
          <div class="modal-header">
            <h3 class="modal-title" id="modalStoryTitle">Food Matters</h3>
            <button class="modal-close" onclick="document.querySelector('#newsStoryModal').classList.remove('open')">✕</button>
          </div>
          <div class="modal-body">
            <img id="modalStoryImg" src="" alt="Story Image" style="width:100%; height:220px; object-fit:cover; border-radius:var(--radius-lg); margin-bottom:var(--sp-4);">
            <div id="modalStoryMeta" style="font-size:0.8rem; color:var(--alms-brown); font-weight:600; margin-bottom:var(--sp-2);"></div>
            <div id="modalStoryBody" style="font-size:0.95rem; line-height:1.7; color:var(--color-text);"></div>
          </div>
          <div class="modal-footer">
            <button class="btn btn-secondary" onclick="document.querySelector('#newsStoryModal').classList.remove('open')">Close</button>
          </div>
        </div>
      </div>
    `;
  },

  updateView() {
    const track = document.getElementById('newsTrack');
    if (track) {
      const isMobile = window.innerWidth < 768;
      const offset = isMobile ? this.currentIndex * 100 : this.currentIndex * 33.333;
      track.style.transform = `translateX(-${offset}%)`;
    }
    document.querySelectorAll('#newsDots .news-dot').forEach((d, idx) => {
      d.classList.toggle('active', idx === this.currentIndex);
    });
  },

  next() {
    this.currentIndex = (this.currentIndex + 1) % this.articles.length;
    this.updateView();
    this.resetTimer();
  },

  prev() {
    this.currentIndex = (this.currentIndex - 1 + this.articles.length) % this.articles.length;
    this.updateView();
    this.resetTimer();
  },

  goTo(idx) {
    this.currentIndex = idx;
    this.updateView();
    this.resetTimer();
  },

  startAutoPlay() {
    this.autoTimer = setInterval(() => {
      this.next();
    }, 5000);
  },

  resetTimer() {
    clearInterval(this.autoTimer);
    this.startAutoPlay();
  },

  openArticle(id) {
    const art = this.articles.find(a => a.id === id);
    if (!art) return;

    document.getElementById('modalStoryTitle').textContent = art.title;
    document.getElementById('modalStoryImg').src = art.image;
    document.getElementById('modalStoryMeta').textContent = `${art.category} • ${art.date} • ${art.readTime}`;
    document.getElementById('modalStoryBody').innerHTML = art.fullContent;
    
    document.getElementById('newsStoryModal').classList.add('open');
  },

  closeModal(e) {
    if (e.target.classList.contains('modal-backdrop')) {
      e.target.classList.remove('open');
    }
  }
};

document.addEventListener('DOMContentLoaded', () => {
  ALMS_NEWS.init();
});
